### ISSUE TITLE
Group the settings

### ISSUE THREAD

**Issue by Madis0** [isXander/OptionsRemastered#4]
Similar settings should be grouped for improved readability.

Chat settings could be grouped like that, though some options may be reorganized
![](https://cdn.discordapp.com/attachments/1024019622548221993/1024034868570632324/unknown.png)

Accessibility settings:

- effects 
- narrator-subtitles-text 
- monochrome logo

Skin:

- hat
- cape-jacket-sleeves
- legs

Music:

- master-**surround sound** - surround sound is currently entirely missing
- music-jukebox
- weather-blocks-ambient
- creatures-players-speech

**Comment by isXander** [comment]
Sound sorting cannot be changed, it just iterates through the enum, same with the skin layers.
